CREATE TABLE country (
    id SERIAL NOT NULL PRIMARY KEY,
    alpha2 CHAR(2) NOT NULL,
    alpha3 CHAR(3) NOT NULL,
    label VARCHAR(64) NOT NULL
);

INSERT INTO country (alpha2, alpha3, label)
VALUES
('AF', 'AFG', 'Afghanistan'),
('AL', 'ALB', 'Albanie'),
('AQ', 'ATA', 'Antarctique'),
('DZ', 'DZA', 'Algérie'),
('AS', 'ASM', 'Samoa Américaines'),
('AD', 'AND', 'Andorre'),
('AO', 'AGO', 'Angola'),
('AG', 'ATG', 'Antigua-et-Barbuda'),
('AZ', 'AZE', 'Azerbaïdjan'),
('AR', 'ARG', 'Argentine'),
('AU', 'AUS', 'Australie'),
('AT', 'AUT', 'Autriche'),
('BS', 'BHS', 'Bahamas'),
('BH', 'BHR', 'Bahreïn'),
('BD', 'BGD', 'Bangladesh'),
('AM', 'ARM', 'Arménie'),
('BB', 'BRB', 'Barbade'),
('BE', 'BEL', 'Belgique'),
('BM', 'BMU', 'Bermudes'),
('BT', 'BTN', 'Bhoutan'),
('BO', 'BOL', 'Bolivie'),
('BA', 'BIH', 'Bosnie-Herzégovine'),
('BW', 'BWA', 'Botswana'),
('BV', 'BVT', 'Île Bouvet'),
('BR', 'BRA', 'Brésil'),
('BZ', 'BLZ', 'Belize'),
('IO', 'IOT', 'Territoire Britannique de l''Océan Indien'),
('SB', 'SLB', 'Îles Salomon'),
('VG', 'VGB', 'Îles Vierges Britanniques'),
('BN', 'BRN', 'Brunéi Darussalam'),
('BG', 'BGR', 'Bulgarie'),
('MM', 'MMR', 'Myanmar'),
('BI', 'BDI', 'Burundi'),
('BY', 'BLR', 'Bélarus'),
('KH', 'KHM', 'Cambodge'),
('CM', 'CMR', 'Cameroun'),
('CA', 'CAN', 'Canada'),
('CV', 'CPV', 'Cap-vert'),
('KY', 'CYM', 'Îles Caïmanes'),
('CF', 'CAF', 'République Centrafricaine'),
('LK', 'LKA', 'Sri Lanka'),
('TD', 'TCD', 'Tchad'),
('CL', 'CHL', 'Chili'),
('CN', 'CHN', 'Chine'),
('TW', 'TWN', 'Taïwan'),
('CX', 'CXR', 'Île Christmas'),
('CC', 'CCK', 'Îles Cocos (Keeling)'),
('CO', 'COL', 'Colombie'),
('KM', 'COM', 'Comores'),
('YT', 'MYT', 'Mayotte'),
('CG', 'COG', 'République du Congo'),
('CD', 'COD', 'République Démocratique du Congo'),
('CK', 'COK', 'Îles Cook'),
('CR', 'CRI', 'Costa Rica'),
('HR', 'HRV', 'Croatie'),
('CU', 'CUB', 'Cuba'),
('CY', 'CYP', 'Chypre'),
('CZ', 'CZE', 'République Tchèque'),
('BJ', 'BEN', 'Bénin'),
('DK', 'DNK', 'Danemark'),
('DM', 'DMA', 'Dominique'),
('DO', 'DOM', 'République Dominicaine'),
('EC', 'ECU', 'Équateur'),
('SV', 'SLV', 'El Salvador'),
('GQ', 'GNQ', 'Guinée Équatoriale'),
('ET', 'ETH', 'Éthiopie'),
('ER', 'ERI', 'Érythrée'),
('EE', 'EST', 'Estonie'),
('FO', 'FRO', 'Îles Féroé'),
('FK', 'FLK', 'Îles (malvinas) Falkland'),
('GS', 'SGS', 'Géorgie du Sud et les Îles Sandwich du Sud'),
('FJ', 'FJI', 'Fidji'),
('FI', 'FIN', 'Finlande'),
('AX', 'ALA', 'Îles Åland'),
('FR', 'FRA', 'France'),
('GF', 'GUF', 'Guyane Française'),
('PF', 'PYF', 'Polynésie Française'),
('TF', 'ATF', 'Terres Australes Françaises'),
('DJ', 'DJI', 'Djibouti'),
('GA', 'GAB', 'Gabon'),
('GE', 'GEO', 'Géorgie'),
('GM', 'GMB', 'Gambie'),
('PS', 'PSE', 'Territoire Palestinien Occupé'),
('DE', 'DEU', 'Allemagne'),
('GH', 'GHA', 'Ghana'),
('GI', 'GIB', 'Gibraltar'),
('KI', 'KIR', 'Kiribati'),
('GR', 'GRC', 'Grèce'),
('GL', 'GRL', 'Groenland'),
('GD', 'GRD', 'Grenade'),
('GP', 'GLP', 'Guadeloupe'),
('GU', 'GUM', 'Guam'),
('GT', 'GTM', 'Guatemala'),
('GN', 'GIN', 'Guinée'),
('GY', 'GUY', 'Guyana'),
('HT', 'HTI', 'Haïti'),
('HM', 'HMD', 'Îles Heard et Mcdonald'),
('VA', 'VAT', 'Saint-Siège (état de la Cité du Vatican)'),
('HN', 'HND', 'Honduras'),
('HK', 'HKG', 'Hong-Kong'),
('HU', 'HUN', 'Hongrie'),
('IS', 'ISL', 'Islande'),
('IN', 'IND', 'Inde'),
('ID', 'IDN', 'Indonésie'),
('IR', 'IRN', 'République Islamique d''Iran'),
('IQ', 'IRQ', 'Iraq'),
('IE', 'IRL', 'Irlande'),
('IL', 'ISR', 'Israël'),
('IT', 'ITA', 'Italie'),
('CI', 'CIV', 'Côte d''Ivoire'),
('JM', 'JAM', 'Jamaïque'),
('JP', 'JPN', 'Japon'),
('KZ', 'KAZ', 'Kazakhstan'),
('JO', 'JOR', 'Jordanie'),
('KE', 'KEN', 'Kenya'),
('KP', 'PRK', 'République Populaire Démocratique de Corée'),
('KR', 'KOR', 'République de Corée'),
('KW', 'KWT', 'Koweït'),
('KG', 'KGZ', 'Kirghizistan'),
('LA', 'LAO', 'République Démocratique Populaire Lao'),
('LB', 'LBN', 'Liban'),
('LS', 'LSO', 'Lesotho'),
('LV', 'LVA', 'Lettonie'),
('LR', 'LBR', 'Libéria'),
('LY', 'LBY', 'Jamahiriya Arabe Libyenne'),
('LI', 'LIE', 'Liechtenstein'),
('LT', 'LTU', 'Lituanie'),
('LU', 'LUX', 'Luxembourg'),
('MO', 'MAC', 'Macao'),
('MG', 'MDG', 'Madagascar'),
('MW', 'MWI', 'Malawi'),
('MY', 'MYS', 'Malaisie'),
('MV', 'MDV', 'Maldives'),
('ML', 'MLI', 'Mali'),
('MT', 'MLT', 'Malte'),
('MQ', 'MTQ', 'Martinique'),
('MR', 'MRT', 'Mauritanie'),
('MU', 'MUS', 'Maurice'),
('MX', 'MEX', 'Mexique'),
('MC', 'MCO', 'Monaco'),
('MN', 'MNG', 'Mongolie'),
('MD', 'MDA', 'République de Moldova'),
('MS', 'MSR', 'Montserrat'),
('MA', 'MAR', 'Maroc'),
('MZ', 'MOZ', 'Mozambique'),
('OM', 'OMN', 'Oman'),
('NA', 'NAM', 'Namibie'),
('NR', 'NRU', 'Nauru'),
('NP', 'NPL', 'Népal'),
('NL', 'NLD', 'Pays-Bas'),
('AN', 'ANT', 'Antilles Néerlandaises'),
('AW', 'ABW', 'Aruba'),
('NC', 'NCL', 'Nouvelle-Calédonie'),
('VU', 'VUT', 'Vanuatu'),
('NZ', 'NZL', 'Nouvelle-Zélande'),
('NI', 'NIC', 'Nicaragua'),
('NE', 'NER', 'Niger'),
('NG', 'NGA', 'Nigéria'),
('NU', 'NIU', 'Niué'),
('NF', 'NFK', 'Île Norfolk'),
('NO', 'NOR', 'Norvège'),
('MP', 'MNP', 'Îles Mariannes du Nord'),
('UM', 'UMI', 'Îles Mineures Éloignées des États-Unis'),
('FM', 'FSM', 'États Fédérés de Micronésie'),
('MH', 'MHL', 'Îles Marshall'),
('PW', 'PLW', 'Palaos'),
('PK', 'PAK', 'Pakistan'),
('PA', 'PAN', 'Panama'),
('PG', 'PNG', 'Papouasie-Nouvelle-Guinée'),
('PY', 'PRY', 'Paraguay'),
('PE', 'PER', 'Pérou'),
('PH', 'PHL', 'Philippines'),
('PN', 'PCN', 'Pitcairn'),
('PL', 'POL', 'Pologne'),
('PT', 'PRT', 'Portugal'),
('GW', 'GNB', 'Guinée-Bissau'),
('TL', 'TLS', 'Timor-Leste'),
('PR', 'PRI', 'Porto Rico'),
('QA', 'QAT', 'Qatar'),
('RE', 'REU', 'Réunion'),
('RO', 'ROU', 'Roumanie'),
('RU', 'RUS', 'Fédération de Russie'),
('RW', 'RWA', 'Rwanda'),
('SH', 'SHN', 'Sainte-Hélène'),
('KN', 'KNA', 'Saint-Kitts-et-Nevis'),
('AI', 'AIA', 'Anguilla'),
('LC', 'LCA', 'Sainte-Lucie'),
('PM', 'SPM', 'Saint-Pierre-et-Miquelon'),
('VC', 'VCT', 'Saint-Vincent-et-les Grenadines'),
('SM', 'SMR', 'Saint-Marin'),
('ST', 'STP', 'Sao Tomé-et-Principe'),
('SA', 'SAU', 'Arabie Saoudite'),
('SN', 'SEN', 'Sénégal'),
('SC', 'SYC', 'Seychelles'),
('SL', 'SLE', 'Sierra Leone'),
('SG', 'SGP', 'Singapour'),
('SK', 'SVK', 'Slovaquie'),
('VN', 'VNM', 'Viet Nam'),
('SI', 'SVN', 'Slovénie'),
('SO', 'SOM', 'Somalie'),
('ZA', 'ZAF', 'Afrique du Sud'),
('ZW', 'ZWE', 'Zimbabwe'),
('ES', 'ESP', 'Espagne'),
('EH', 'ESH', 'Sahara Occidental'),
('SD', 'SDN', 'Soudan'),
('SR', 'SUR', 'Suriname'),
('SJ', 'SJM', 'Svalbard etÎle Jan Mayen'),
('SZ', 'SWZ', 'Swaziland'),
('SE', 'SWE', 'Suède'),
('CH', 'CHE', 'Suisse'),
('SY', 'SYR', 'République Arabe Syrienne'),
('TJ', 'TJK', 'Tadjikistan'),
('TH', 'THA', 'Thaïlande'),
('TG', 'TGO', 'Togo'),
('TK', 'TKL', 'Tokelau'),
('TO', 'TON', 'Tonga'),
('TT', 'TTO', 'Trinité-et-Tobago'),
('AE', 'ARE', 'Émirats Arabes Unis'),
('TN', 'TUN', 'Tunisie'),
('TR', 'TUR', 'Turquie'),
('TM', 'TKM', 'Turkménistan'),
('TC', 'TCA', 'Îles Turks et Caïques'),
('TV', 'TUV', 'Tuvalu'),
('UG', 'UGA', 'Ouganda'),
('UA', 'UKR', 'Ukraine'),
('MK', 'MKD', 'L''ex-République Yougoslave de Macédoine'),
('EG', 'EGY', 'Égypte'),
('GB', 'GBR', 'Royaume-Uni'),
('IM', 'IMN', 'Île de Man'),
('TZ', 'TZA', 'République-Unie de Tanzanie'),
('US', 'USA', 'États-Unis'),
('VI', 'VIR', 'Îles Vierges des États-Unis'),
('BF', 'BFA', 'Burkina Faso'),
('UY', 'URY', 'Uruguay'),
('UZ', 'UZB', 'Ouzbékistan'),
('VE', 'VEN', 'Venezuela'),
('WF', 'WLF', 'Wallis et Futuna'),
('WS', 'WSM', 'Samoa'),
('YE', 'YEM', 'Yémen'),
('CS', 'SCG', 'Serbie-et-Monténégro'),
('ZM', 'ZMB', 'Zambie');

CREATE TABLE customer (
    id SERIAL NOT NULL PRIMARY KEY,
    lastname VARCHAR(64) NOT NULL,
    firstname VARCHAR(64) NOT NULL,
    birthdate DATE NOT NULL
);

INSERT INTO customer (lastname, firstname, birthdate) VALUES
('Potter', 'Harry', '1980-08-31'),
('Weasley', 'Ron', '1980-03-01'),
('Granger', 'Hermione', '1979-09-19'),
('Rogue', 'Severus', '1960-01-09'),
('Evans', 'Lily', '1960-01-30'),
('Potter', 'James', '1960-03-27'),
('Weasley', 'Ginny', '1981-08-11'),
('McGonagall', 'Minerva', '1935-10-04'),
('Black', 'Sirius', '1959-11-03'),
('Hagrid', 'Rubeus', '1928-12-06');
